//
//  ImageCollectionWords+ImageNames.swift
//  BitWizard
//
//  Created by Nicky Taylor on 12/11/22.
//

import Foundation

extension ImageCollectionWords {
    
    static func imageNames() -> [String] {
        let text = """
        absent_minded.png
        achieve.png
        active.png
        adult.png
        air_plane.png
        always_ready.png
        appeal.png
        appeared.png
        arm_chair.png
        awkward_silence.png
        back_pack.png
        bad_advice.png
        bagel.png
        banana_split.png
        beard_trimmer.png
        beginner.png
        bicycle.png
        birthday_hat.png
        blow_dart.png
        booklet.png
        brain_surgery.png
        broccoli.png
        buffet.png
        calendar.png
        calm.png
        carp_pond.png
        chair.png
        chemically_imbalanced.png
        class_clown.png
        crayon.png
        cremation.png
        cricket.png
        curler.png
        custody.png
        cyclone.png
        damage.png
        dance.png
        dead.png
        decide.png
        deficit.png
        deflate.png
        delay.png
        delete.png
        denial.png
        deposit.png
        desk.png
        devour.png
        dew.png
        dialog.png
        diet.png
        doing_nothing.png
        driver.png
        edible.png
        element.png
        energy.png
        engine.png
        evidence.png
        extra_calories.png
        fact.png
        farmer.png
        feather.png
        feature.png
        fiber.png
        fighting.png
        fish.png
        flag_pole.png
        floor_boards.png
        flyers.png
        focus.png
        foot_print.png
        fore_head.png
        fork.png
        free_of_charge.png
        friday.png
        front_yard.png
        fruit_salad.png
        garage.png
        garden.png
        geometry.png
        ghost.png
        giraffe.png
        glider.png
        gold_fish.png
        gong.png
        gummy_bear.png
        hamster.png
        heat.png
        hill.png
        hobbies.png
        invite.png
        island.png
        kale.png
        karate.png
        kitty.png
        lasagna.png
        lettuce.png
        luggage.png
        m_m_s.png
        mail_box.png
        metal_bucket.png
        milky_way.png
        mirror.png
        modern.png
        mountain.png
        mouth.png
        napkin.png
        noodle.png
        october.png
        opposite.png
        orchid.png
        ornament.png
        owner.png
        oxygen.png
        pain_killers.png
        pain.png
        pair.png
        palm.png
        panda.png
        panic.png
        paper.png
        paradox.png
        park_bench.png
        parrot.png
        patch.png
        picket_fence.png
        picture.png
        pink_cloud.png
        pizza_dough.png
        place_mats.png
        planet.png
        plankton.png
        plastic.png
        played.png
        plaza.png
        pliers.png
        pond.png
        pony.png
        possible.png
        prank_call.png
        predict.png
        pregnant.png
        press.png
        pulled.png
        purple.png
        quiet.png
        radius.png
        rain.png
        rainbow.png
        rake.png
        ranch.png
        rate.png
        ray.png
        red.png
        refund.png
        regret.png
        relative.png
        relax.png
        robot.png
        salad.png
        samurai.png
        season.png
        sheep.png
        shield.png
        sign_here.png
        slime.png
        stove.png
        sub_way.png
        surprise.png
        teeth.png
        toast.png
        traffic.png
        trigger.png
        trout.png
        tuna.png
        twizzler.png
        uneasy.png
        untrue.png
        useless.png
        vase.png
        veggies.png
        verdict.png
        viral.png
        vision.png
        volcano.png
        walrus.png
        warning_shot.png
        watch.png
        wax_museum.png
        weapon.png
        weather.png
        weight.png
        wheel.png
        whiskers.png
        wind_shield.png
        wings.png
        wire.png
        wound.png
        yarn_ball.png
        zone.png
        """
        return textToLines(imageListText: text)
    }
    
}
